-- Updated table schema to match actual database structure
-- Tables for Press 1
CREATE TABLE IF NOT EXISTS press1_pb (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press1_pm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press1_mem (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press1_cm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

-- Tables for Press 2
CREATE TABLE IF NOT EXISTS press2_pb (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press2_pm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press2_mem (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press2_cm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

-- Tables for Press 3
CREATE TABLE IF NOT EXISTS press3_pb (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press3_pm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press3_mem (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press3_cm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

-- Tables for Press 4
CREATE TABLE IF NOT EXISTS press4_pb (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press4_pm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press4_mem (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);

CREATE TABLE IF NOT EXISTS press4_cm (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  _NAME VARCHAR(64),
  _NUMERICID INT,
  _VALUE VARCHAR(64),
  _TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _QUALITY INT
);
